// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: create_room.sql

package database

import (
	"context"
)

const createRoom = `-- name: CreateRoom :one
INSERT INTO room(id, created_at, updated_at,room_name)
VALUES (
    gen_random_uuid(),
    NOW(),
    NOW(),
    $1
)
RETURNING id, created_at, updated_at, room_name
`

func (q *Queries) CreateRoom(ctx context.Context, roomName string) (Room, error) {
	row := q.db.QueryRowContext(ctx, createRoom, roomName)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RoomName,
	)
	return i, err
}
