// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: delete_room.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const deleteRoom = `-- name: DeleteRoom :one
DELETE FROM rooms
WHERE id = $1
RETURNING id, created_at, updated_at, room_name
`

func (q *Queries) DeleteRoom(ctx context.Context, id uuid.UUID) (Room, error) {
	row := q.db.QueryRowContext(ctx, deleteRoom, id)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RoomName,
	)
	return i, err
}
