// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: delete_msg.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const deleteMessage = `-- name: DeleteMessage :one
DELETE FROM message
WHERE id = $1
RETURNING id, created_at, updated_at, body, room_id, user_id
`

func (q *Queries) DeleteMessage(ctx context.Context, id uuid.UUID) (Message, error) {
	row := q.db.QueryRowContext(ctx, deleteMessage, id)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Body,
		&i.RoomID,
		&i.UserID,
	)
	return i, err
}
