// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: delete_user.sql

package database

import (
	"context"
)

const deleteUserByUsername = `-- name: DeleteUserByUsername :one
DELETE FROM users
WHERE username = $1
RETURNING id, username, created_at, updated_at, hashed_password
`

func (q *Queries) DeleteUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, deleteUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.HashedPassword,
	)
	return i, err
}
