// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: get_msg_usr.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getMessagesUser = `-- name: GetMessagesUser :one
SELECT id, created_at, updated_at, body, room_id, user_id FROM message
WHERE user_id = $1
`

func (q *Queries) GetMessagesUser(ctx context.Context, userID uuid.UUID) (Message, error) {
	row := q.db.QueryRowContext(ctx, getMessagesUser, userID)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Body,
		&i.RoomID,
		&i.UserID,
	)
	return i, err
}
