// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: get_all_rooms.sql

package database

import (
	"context"
)

const getAllRoomNames = `-- name: GetAllRoomNames :many
SELECT room_name FROM room
`

func (q *Queries) GetAllRoomNames(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getAllRoomNames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var room_name string
		if err := rows.Scan(&room_name); err != nil {
			return nil, err
		}
		items = append(items, room_name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
