// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: get_room.sql

package database

import (
	"context"
)

const getRoomByRoomName = `-- name: GetRoomByRoomName :one
SELECT room_name
FROM room
WHERE room_name = $1
`

func (q *Queries) GetRoomByRoomName(ctx context.Context, roomName string) (string, error) {
	row := q.db.QueryRowContext(ctx, getRoomByRoomName, roomName)
	var room_name string
	err := row.Scan(&room_name)
	return room_name, err
}
