// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: get_room.sql

package database

import (
	"context"
)

const getRoomByRoomName = `-- name: GetRoomByRoomName :one
SELECT id, created_at, updated_at, room_name
FROM rooms
WHERE room_name = $1
`

func (q *Queries) GetRoomByRoomName(ctx context.Context, roomName string) (Room, error) {
	row := q.db.QueryRowContext(ctx, getRoomByRoomName, roomName)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RoomName,
	)
	return i, err
}
