// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: get_msg_room.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getMessagesRoom = `-- name: GetMessagesRoom :one
SELECT id, created_at, updated_at, body, room_id, user_id FROM message
WHERE room_id = $1
`

func (q *Queries) GetMessagesRoom(ctx context.Context, roomID uuid.UUID) (Message, error) {
	row := q.db.QueryRowContext(ctx, getMessagesRoom, roomID)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Body,
		&i.RoomID,
		&i.UserID,
	)
	return i, err
}
