// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type Message struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Body      string
	RoomID    uuid.UUID
	UserID    uuid.UUID
}

type Room struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	RoomName  string
}

type User struct {
	ID             uuid.UUID
	Username       string
	CreatedAt      time.Time
	UpdatedAt      time.Time
	HashedPassword string
}
